### ISSUE TITLE
CrashLoopBackOff installing v.33.0

### ISSUE THREAD

**Issue by thomasliddledba** [aws/karpenter-provider-aws#5340]
### Description

**Observed Behavior**:
When following the directions on the [Getting Started](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/) page and checking on the pods after [Step 4](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/#4-install-karpenter), I'm running into a `CrashLoopBackOff` on the pods. After looking at the logs for one of the pods in the `kube-system` namespace, I see the following when doing a `kubectl logs` on one of the pods.
```bash
$ kubectl logs karpenter-55d98687c9-9k9xx 
```
```text
panic: validating options, missing field, cluster-name

goroutine 1 [running]:
github.com/samber/lo.must({0x25cae80, 0xc000208c80}, {0x0, 0x0, 0x0})
        github.com/samber/lo@v1.39.0/errors.go:53 +0x1e9
github.com/samber/lo.Must0(...)
        github.com/samber/lo@v1.39.0/errors.go:72
sigs.k8s.io/karpenter/pkg/operator/injection.WithOptionsOrDie({0x30bf5f8, 0xc00092f980}, {0xc000141f20, 0x2, 0x2332e20?})
        sigs.k8s.io/karpenter@v0.33.0/pkg/operator/injection/injection.go:51 +0x138
sigs.k8s.io/karpenter/pkg/operator.NewOperator()
        sigs.k8s.io/karpenter@v0.33.0/pkg/operator/operator.go:84 +0xb7
main.main()
        github.com/aws/karpenter/cmd/controller/main.go:33 +0x25
```

**Expected Behavior**:
My expectation is that the pods would be in a `Running` state.

**Reproduction Steps** (Please include YAML):

**Versions**: `v.33.0`
- Chart Version: `karpenter-v0.33.0`
- Kubernetes Version (`kubectl version`):
```bash
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4-eks-8cb36c9
```
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Can you share your deployment configuration that you are using here? Might also help to give the helm values you are passing through if you are using helm to install.

**Comment by thomasliddledba** [comment]
Hi Jonathan
I'm using the instructions in the [Getting Started](https://karpenter.sh/docs/getting-started/getting-started-with-karpenter/) page.

Here is the command I ran per the instructions.
```bash
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
  # Optionally run on fargate or on k8s 1.23
  # --set "serviceAccount.annotations.eks\.amazonaws\.com/role-arn=${KARPENTER_IAM_ROLE_ARN}" \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}" \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait
```

**Comment by mikkoc** [comment]
We just hit the same issue when upgrading from `0.32.3` to `0.33`. We had to revert.

**Comment by sde-melo** [comment]
Same. All AWS node templates and provisioners have been deleted!

**Comment by njtran** [comment]
I believe this might be a problem with the in-line comment in the install command. For those who ran into this, can you try removing the comment and seeing if this works? Removing the comment for myself works. 

```
helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
  --set "settings.clusterName=${CLUSTER_NAME}" \
  --set "settings.interruptionQueue=${CLUSTER_NAME}" \
  --set controller.resources.requests.cpu=1 \
  --set controller.resources.requests.memory=1Gi \
  --set controller.resources.limits.cpu=1 \
  --set controller.resources.limits.memory=1Gi \
  --wait
```

**Comment by mikkoc** [comment]
We are using the Helm Terraform provider to install/upgrade the chart, not the helm command.

**Comment by thomasliddledba** [comment]
> I believe this might be a problem with the in-line comment in the install command. For those who ran into this, can you try removing the comment and seeing if this works? Removing the comment for myself works.
> 
> ```
> helm upgrade --install karpenter oci://public.ecr.aws/karpenter/karpenter --version "${KARPENTER_VERSION}" --namespace "${KARPENTER_NAMESPACE}" --create-namespace \
>   --set "settings.clusterName=${CLUSTER_NAME}" \
>   --set "settings.interruptionQueue=${CLUSTER_NAME}" \
>   --set controller.resources.requests.cpu=1 \
>   --set controller.resources.requests.memory=1Gi \
>   --set controller.resources.limits.cpu=1 \
>   --set controller.resources.limits.memory=1Gi \
>   --wait
> ```

Hi @njtran 
This install command works for me.  I was able to check the pods and confirm they are running. Does the documentation need to be updated to remove this comment in [Step 4](https://karpenter.sh/v0.33/getting-started/getting-started-with-karpenter/#4-install-karpenter)?

```text
# Logout of helm registry to perform an unauthenticated pull against the public ECR
```

**Comment by jonathan-innis** [comment]
. Here is the command I ran per the instructions

**Comment by sde-melo** [comment]
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "21"
    meta.helm.sh/release-name: karpenter
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-07-22T14:07:41Z"
  generation: 21
  labels:
    app.kubernetes.io/instance: karpenter
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: karpenter
    app.kubernetes.io/version: 0.31.1
    helm.sh/chart: karpenter-v0.31.1
  name: karpenter
  namespace: kube-system
  resourceVersion: "571743682"
  uid: 81b474d0-8f89-4245-baba-8d692f812401
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/name: karpenter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/settings: fa31024d0527955fdcedb32af4b045d707453b5671c56716d0c61d9e56ebe5a6
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: karpenter
        app.kubernetes.io/name: karpenter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: karpenter
                app.kubernetes.io/name: karpenter
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: KUBERNETES_MIN_VERSION
          value: 1.19.0-0
        - name: KARPENTER_SERVICE
          value: karpenter
        - name: WEBHOOK_PORT
          value: "8443"
        - name: METRICS_PORT
          value: "8000"
        - name: HEALTH_PROBE_PORT
          value: "8081"
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: controller
              divisor: "0"
              resource: limits.memory
        image: public.ecr.aws/karpenter/controller:v0.31.1@sha256:be5da7cb9181c2969280e869c465927de278e17d56762bfa5eeb4b21e5c9762e
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        name: controller
        ports:
        - containerPort: 8000
          name: http-metrics
          protocol: TCP
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 8443
          name: https-webhook
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsGroup: 65536
          runAsNonRoot: true
          runAsUser: 65536
          seccompProfile:
            type: RuntimeDefault
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: karpenter
      serviceAccountName: karpenter
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: singlespot.com/ondemand
        operator: Exists
      - effect: NoSchedule
        key: singlespot.com/spot
        operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: karpenter
            app.kubernetes.io/name: karpenter
        maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-12-18T14:00:50Z"
    lastUpdateTime: "2023-12-18T14:00:50Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-12-18T13:44:03Z"
    lastUpdateTime: "2023-12-18T14:03:58Z"
    message: ReplicaSet "karpenter-6dd7ff6bbc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 21
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
```

We had to remove the finalizer on CRD machines.karpenter.sh after the helm rollback.

**Comment by njtran** [comment]
I notice that your deployment has the following node affinity, which is outdated and should reflect the new nodepool value. You should change the key to be `karpenter.sh/nodepool`  as shown [here](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/values.yaml#L65-L71)

I'm not sure if this would cause a CrashLoopBackOff, but it will ensure that Karpenter isn't scheduled to a node it's provisioned. Also please make sure if this is an existing cluster that you've upgraded to v0.32.x and went through the [migration guide](https://karpenter.sh/docs/upgrading/v1beta1-migration/) before upgrading to v0.33.0.


Your code:
```
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/provisioner-name
                operator: DoesNotExist
```

**Comment by njtran** [comment]
@sde-melo since the original issue is fixed, I'll go ahead and close this. Please feel free to open another ticket if the above advice doesn't help and you're still experiencing issues on v0.33.0.

**Comment by sde-melo** [comment]
Thanks @njtran

**Comment by olibenni** [comment]
For those using the Helm Terraform Provider and are hitting the `panic: validating options, missing field, cluster-name` issue, updating the values file from

```yaml
settings:
  aws:
    clusterName: ...
    clusterEndpoint: ...
    defaultInstanceProfile: ...
```

```yaml
settings:
  clusterName: ...
  clusterEndpoint: ...
  defaultInstanceProfile: ...
```

Should fix it

**Comment by nedema** [comment]
> For those using the Helm Terraform Provider and are hitting the `panic: validating options, missing field, cluster-name` issue, updating the values file from
> 
> ```yaml
> settings:
>   aws:
>     clusterName: ...
>     clusterEndpoint: ...
>     defaultInstanceProfile: ...
> ```
> 
> ```yaml
> settings:
>   clusterName: ...
>   clusterEndpoint: ...
>   defaultInstanceProfile: ...
> ```
> 
> Should fix it

This did not resolve similar issue. Karpenter version `v0.36.2`

**Comment by acarvajalgil** [comment]
This solution resolved my problem:

resource "helm_release" "karpenter" {
  namespace        = "karpenter"
  create_namespace = true

  name       = "karpenter"
  repository = "oci://public.ecr.aws/karpenter"
  chart      = "karpenter"
  version    = "0.35.4"

  set {
    name  = "serviceAccount.annotations.eks\\.amazonaws\\.com/role-arn"
    value = aws_iam_role.karpenter_role.arn
  }

  set {
    name  = "settings.clusterName"
    value = aws_eks_cluster.admiral_cluster.id
  }

  set {
    name  = "settings.clusterEndpoint"
    value = aws_eks_cluster.admiral_cluster.endpoint
  }

  set {
    name  = "settings.defaultInstanceProfile"
    value = aws_iam_instance_profile.karpenter_instance_profile.name
  }

  depends_on = [aws_eks_node_group.private-nodes]
}

**Comment by dali-zhou-veeva** [comment]
> For those using the Helm Terraform Provider and are hitting the `panic: validating options, missing field, cluster-name` issue, updating the values file from
> 
> ```yaml
> settings:
>   aws:
>     clusterName: ...
>     clusterEndpoint: ...
>     defaultInstanceProfile: ...
> ```
> 
> ```yaml
> settings:
>   clusterName: ...
>   clusterEndpoint: ...
>   defaultInstanceProfile: ...
> ```
> 
> Should fix it

This really saved my life,   Karpenter Version 1.0.5,  K8S Version 1.31

**Comment by whchoi98** [comment]
In EKS 1.29, I encountered the same issue, and it was resolved after upgrading to Karpenter 1.0.5.
