### ISSUE TITLE
controller.nodeclaim.consistency error wrong storage size being reported by the controller

### ISSUE THREAD

**Issue by tl-alex-nicot** [aws/karpenter-provider-aws#6177]
### Description

**Observed Behavior**:
karpenter thinks a nodeclaim has the wrong ephemeral storage set 

{"level":"ERROR","time":"2024-05-10T10:23:52.304Z","logger":"controller.nodeclaim.consistency","message":"check failed, expected 300Gi of resource ephemeral-storage, but found 125816812Ki (40.0% of expected)","commit":"2c8f2a5","nodeclaim":"nginx-bsn2h"}

**Expected Behavior**:

I would expect karpenter to know the correct ephemeral storage size

**Reproduction Steps** (Please include YAML):

we have an ec2nodeclass called "default" which indeed has 300Gi of storage 

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "1078616476462511281"
    meta.helm.sh/release-name: karpenter-workers
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2023-11-02T13:15:37Z"
  finalizers:
  - karpenter.k8s.aws/termination
  generation: 3
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default
  resourceVersion: "439476752"
  uid: e8c79922-06c8-4934-8083-b4c9a84ad1dc
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: false
      encrypted: true
      kmsKeyID: arn:aws:kms:eu-west-1:xxxxxxx:key/ff5842b6-4991-4464-80fc-1e1682c8664e
      volumeSize: 300Gi
      volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: development-eu-west-1-karpenter-worker
  securityGroupSelectorTerms:
  - tags:
      cluster/development-eu-west-1/workers: "true"
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery/development-eu-west-1: shared
  tags:
    Infra: EKS
    Name: development-eu-west-1-eks-worker-node
    Product: Shared
    karpenter.sh/discovery: development-eu-west-1
```
our nginx ec2nodeclass is set to have 120 

```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "3386146869567909253"
    meta.helm.sh/release-name: karpenter-workers
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2023-11-02T13:15:37Z"
  finalizers:
  - karpenter.k8s.aws/termination
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: nginx
  resourceVersion: "439330602"
  uid: ce905097-8c23-4f6a-9e20-b10d4fe80dbd
spec:
  amiFamily: AL2
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: false
      encrypted: true
      kmsKeyID: arn:aws:kms:eu-west-1:xxxxxxxx:key/ff5842b6-4991-4464-80fc-1e1682c8664e
      volumeSize: 120Gi
      volumeType: gp3
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: development-eu-west-1-karpenter-worker
  securityGroupSelectorTerms:
  - tags:
      cluster/development-eu-west-1/workers: "true"
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery/development-eu-west-1: shared
  tags:
    Infra: EKS
    Name: development-eu-west-1-eks-nginx-worker-node
    Product: Shared
    karpenter.sh/discovery: development-eu-west-1
```

the nodeclaim itself for some reason also says 300Gi which is odd 

```
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  annotations:
    karpenter.k8s.aws/ec2nodeclass-hash: "3386146869567909253"
    karpenter.k8s.aws/tagged: "true"
    karpenter.sh/managed-by: development-eu-west-1
    karpenter.sh/nodepool-hash: "774805070015068538"
  creationTimestamp: "2024-05-10T09:33:49Z"
  finalizers:
  - karpenter.sh/termination
  generateName: nginx-
  generation: 1
  labels:
    karpenter.k8s.aws/instance-category: c
    karpenter.k8s.aws/instance-cpu: "2"
    karpenter.k8s.aws/instance-encryption-in-transit-supported: "false"
    karpenter.k8s.aws/instance-family: c5
    karpenter.k8s.aws/instance-generation: "5"
    karpenter.k8s.aws/instance-hypervisor: nitro
    karpenter.k8s.aws/instance-memory: "4096"
    karpenter.k8s.aws/instance-network-bandwidth: "750"
    karpenter.k8s.aws/instance-size: large
    karpenter.sh/capacity-type: spot
    karpenter.sh/nodepool: nginx
    kubernetes.io/arch: amd64
    kubernetes.io/os: linux
    node.kubernetes.io/instance-type: c5.large
    node.kubernetes.io/worker-ingress-receiver: "true"
    topology.kubernetes.io/region: eu-west-1
    topology.kubernetes.io/zone: eu-west-1a
  name: nginx-bsn2h
  ownerReferences:
  - apiVersion: karpenter.sh/v1beta1
    blockOwnerDeletion: true
    kind: NodePool
    name: nginx
    uid: 32360463-dcfb-47af-8d50-22ff55ed2ddb
  resourceVersion: "439332711"
  uid: e4997948-e77b-4fc9-8ca6-9a5ac4c94e41
spec:
  kubelet:
    clusterDNS:
    - 169.254.20.10
  nodeClassRef:
    name: nginx
  requirements:
  - key: karpenter.sh/nodepool
    operator: In
    values:
    - nginx
  - key: karpenter.sh/capacity-type
    operator: In
    values:
    - spot
  - key: node.kubernetes.io/worker-ingress-receiver
    operator: In
    values:
    - "true"
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - c5.large
    - c5.xlarge
    - c6a.xlarge
    - c6i.xlarge
    - m5.large
  - key: topology.kubernetes.io/zone
    operator: In
    values:
    - eu-west-1a
  resources:
    requests:
      cpu: 795m
      ephemeral-storage: 3000Mi
      memory: 1921Mi
      pods: "11"
  taints:
  - effect: NoSchedule
    key: nginx
    value: "true"
status:
  allocatable:
    cpu: 1930m
    ephemeral-storage: 269Gi
    memory: 3114Mi
    pods: "29"
    vpc.amazonaws.com/pod-eni: "9"
  capacity:
    cpu: "2"
    ephemeral-storage: 300Gi
    memory: 3788Mi
    pods: "29"
    vpc.amazonaws.com/pod-eni: "9"
  conditions:
  - lastTransitionTime: "2024-05-10T09:34:43Z"
    status: "True"
    type: Initialized
  - lastTransitionTime: "2024-05-10T09:33:52Z"
    status: "True"
    type: Launched
  - lastTransitionTime: "2024-05-10T09:34:43Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-05-10T09:34:30Z"
    status: "True"
    type: Registered
  imageID: ami-007901c6195ae9299
  nodeName: ip-10-110-4-53.eu-west-1.compute.internal
  providerID: aws:///eu-west-1a/i-00885188cccbf6eef
```
I have check the actual storage of the ec2 and it is 120Gi which matches what the ec2nodeclass says

this is the nginx nodepool and you can see it references the nginx nodeclass I posted 

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "774805070015068538"
    meta.helm.sh/release-name: karpenter-workers
    meta.helm.sh/release-namespace: karpenter
  creationTimestamp: "2023-11-02T13:15:37Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: nginx
  resourceVersion: "439773588"
  uid: 32360463-dcfb-47af-8d50-22ff55ed2ddb
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  template:
    spec:
      kubelet:
        clusterDNS:
        - 169.254.20.10
      nodeClassRef:
        name: nginx
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: node.kubernetes.io/worker-ingress-receiver
        operator: In
        values:
        - "true"
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c5.xlarge
        - c6i.xlarge
        - c6a.xlarge
        - c5.large
        - m5.large
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - eu-west-1a
        - eu-west-1b
        - eu-west-1c
      taints:
      - effect: NoSchedule
        key: nginx
        value: "true"
status:
  resources:
    cpu: "4"
    ephemeral-storage: 251633624Ki
    memory: 11698036Ki
    pods: "58"
```

**Versions**:
- Chart Version: 0.35.0
- Kubernetes Version (`kubectl version`): 
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.3-eks-adc7111

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
From the commit, I can see that you're running `v0.35.0`. That version has [a bug in it](https://github.com/aws/karpenter-provider-aws/pull/5816) that was resolved in later patch versions. I'd recommend either updating to the latest version (`v0.36.1`) or just upgrading to the latest patch version on your current minor version (`v0.35.4`) to get the fix.

**Comment by tl-alex-nicot** [comment]
Hi Jonathan, I just bumped to 0.36.1 and can still see the error

```
{"level":"INFO","time":"2024-05-13T11:56:11.838Z","logger":"controller","message":"webhook disabled","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:11.838Z","logger":"controller.controller-runtime.metrics","message":"Starting metrics server","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:11.839Z","logger":"controller.controller-runtime.metrics","message":"Serving metrics server","commit":"fb4d75f","bindAddress":":8000","secure":false}
{"level":"INFO","time":"2024-05-13T11:56:11.838Z","logger":"controller","message":"starting server","commit":"fb4d75f","kind":"health probe","addr":"[::]:8081"}
{"level":"INFO","time":"2024-05-13T11:56:12.139Z","logger":"controller","message":"attempting to acquire leader lease karpenter/karpenter-leader-election...","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.236Z","logger":"controller","message":"successfully acquired lease karpenter/karpenter-leader-election","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.236Z","logger":"controller.provisioner","message":"starting controller","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.236Z","logger":"controller.disruption.queue","message":"starting controller","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.236Z","logger":"controller.eviction-queue","message":"starting controller","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"provisioner.trigger.pod","controllerGroup":"","controllerKind":"Pod","source":"kind source: *v1.Pod"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"provisioner.trigger.pod","controllerGroup":"","controllerKind":"Pod"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller.disruption","message":"starting controller","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodepool.hash","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"nodepool.hash","controllerGroup":"karpenter.sh","controllerKind":"NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"provisioner.trigger.node","controllerGroup":"","controllerKind":"Node","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"provisioner.trigger.node","controllerGroup":"","controllerKind":"Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"state.node","controllerGroup":"","controllerKind":"Node","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"state.node","controllerGroup":"","controllerKind":"Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"state.daemonset","controllerGroup":"apps","controllerKind":"DaemonSet","source":"kind source: *v1.DaemonSet"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"state.daemonset","controllerGroup":"apps","controllerKind":"DaemonSet"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"state.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"state.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"state.pod","controllerGroup":"","controllerKind":"Pod","source":"kind source: *v1.Pod"}
{"level":"INFO","time":"2024-05-13T11:56:12.237Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"state.pod","controllerGroup":"","controllerKind":"Pod"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"node.termination","controllerGroup":"","controllerKind":"Node","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"node.termination","controllerGroup":"","controllerKind":"Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"state.nodeclaim","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"state.nodeclaim","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"metrics.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"metrics.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"metrics.pod","controllerGroup":"","controllerKind":"Pod","source":"kind source: *v1.Pod"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"metrics.pod","controllerGroup":"","controllerKind":"Pod"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller.metrics.node","message":"starting controller","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1.Node"}
{"level":"INFO","time":"2024-05-13T11:56:12.238Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller.nodeclaim.garbagecollection","message":"starting controller","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"lease.garbagecollection","controllerGroup":"coordination.k8s.io","controllerKind":"Lease","source":"kind source: *v1.Lease"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"lease.garbagecollection","controllerGroup":"coordination.k8s.io","controllerKind":"Lease"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodePool"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1.Pod"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *unstructured.Unstructured"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller.nodeclaim.garbagecollection","message":"starting controller","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","source":"kind source: *v1beta1.EC2NodeClass"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller.pricing","message":"starting controller","commit":"fb4d75f"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting EventSource","commit":"fb4d75f","controller":"nodeclaim.tagging","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","source":"kind source: *v1beta1.NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.239Z","logger":"controller","message":"Starting Controller","commit":"fb4d75f","controller":"nodeclaim.tagging","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim"}
{"level":"INFO","time":"2024-05-13T11:56:12.337Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"nodepool.hash","controllerGroup":"karpenter.sh","controllerKind":"NodePool","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.337Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"state.node","controllerGroup":"","controllerKind":"Node","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.337Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"provisioner.trigger.node","controllerGroup":"","controllerKind":"Node","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.338Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"provisioner.trigger.pod","controllerGroup":"","controllerKind":"Pod","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.343Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"metrics.pod","controllerGroup":"","controllerKind":"Pod","worker count":1}
{"level":"INFO","time":"2024-05-13T11:56:12.343Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"nodepool.counter","controllerGroup":"karpenter.sh","controllerKind":"NodePool","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.343Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.343Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":1000}
{"level":"INFO","time":"2024-05-13T11:56:12.344Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":100}
{"level":"INFO","time":"2024-05-13T11:56:12.344Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"nodeclaim.tagging","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":1}
{"level":"ERROR","time":"2024-05-13T11:56:12.344Z","logger":"controller.nodeclaim.consistency","message":"check failed, expected 300Gi of resource ephemeral-storage, but found 125816812Ki (40.0% of expected)","commit":"fb4d75f","nodeclaim":"nginx-bsn2h"}
{"level":"INFO","time":"2024-05-13T11:56:12.347Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"nodeclaim.disruption","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.355Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"nodeclass","controllerGroup":"karpenter.k8s.aws","controllerKind":"EC2NodeClass","worker count":10}
{"level":"ERROR","time":"2024-05-13T11:56:12.356Z","logger":"controller.nodeclaim.consistency","message":"check failed, expected 300Gi of resource ephemeral-storage, but found 125816812Ki (40.0% of expected)","commit":"fb4d75f","nodeclaim":"nginx-9v9cf"}
{"level":"INFO","time":"2024-05-13T11:56:12.441Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"state.daemonset","controllerGroup":"apps","controllerKind":"DaemonSet","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.443Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"state.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.443Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"state.nodeclaim","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.443Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"lease.garbagecollection","controllerGroup":"coordination.k8s.io","controllerKind":"Lease","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.443Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"metrics.nodepool","controllerGroup":"karpenter.sh","controllerKind":"NodePool","worker count":1}
{"level":"INFO","time":"2024-05-13T11:56:12.443Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"state.pod","controllerGroup":"","controllerKind":"Pod","worker count":10}
{"level":"INFO","time":"2024-05-13T11:56:12.444Z","logger":"controller","message":"Starting workers","commit":"fb4d75f","controller":"node.termination","controllerGroup":"","controllerKind":"Node","worker count":100
```

**Comment by tl-alex-nicot** [comment]
oh wait I bet its because the nodeclaims have not been replaced since upgrading so it reports on them being wrong
