### ISSUE TITLE
Karpenter 1.3 - ec2nodeclass not ready

### ISSUE THREAD

**Issue by Vormillion** [aws/karpenter-provider-aws#7872]
### Description

**Observed Behavior**: Ec2nodeclass is not ready after upgrade to Karpenter 1.3. Everything works fine with 1.2. Ec2nodeclass reports ec2:runInstances issue, but according to docs IAM policy didn't change and ec2:runInstances permission is still there.

**Expected Behavior**: ec2nodeclass should work

**Reproduction Steps** (Please include YAML):
```
apiVersion: v1
items:
- apiVersion: karpenter.k8s.aws/v1
  kind: EC2NodeClass
  metadata:
    annotations:
      karpenter.k8s.aws/ec2nodeclass-hash: "2914232624768264253"
      karpenter.k8s.aws/ec2nodeclass-hash-version: v4
      karpenter.sh/stored-version-migrated: "true"
    creationTimestamp: "2024-03-15T10:59:07Z"
    finalizers:
    - karpenter.k8s.aws/termination
    generation: 5
    name: default
    resourceVersion: "180814102"
    uid: 41dcb863-0804-4974-b3c4-a9d4ce494ea7
  spec:
    amiSelectorTerms:
    - alias: al2@latest
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        iops: 3000
        throughput: 125
        volumeSize: 100Gi
        volumeType: gp3
    metadataOptions:
      httpEndpoint: enabled
      httpProtocolIPv6: disabled
      httpPutResponseHopLimit: 2
      httpTokens: required
    role: xxx-eks
    securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: xxx-eks
    subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: xxx-eks
    userData: |
      #!/bin/bash
      echo "$(jq '.podPidsLimit=1000' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
  status:
    amis:
    - id: ami-0a48515b75da67625
      name: amazon-eks-node-1.32-v20250228
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: DoesNotExist
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: DoesNotExist
    conditions:
    - lastTransitionTime: "2025-03-10T16:13:40Z"
      message: ""
      observedGeneration: 5
      reason: AMIsReady
      status: "True"
      type: AMIsReady
    - lastTransitionTime: "2025-03-10T16:13:40Z"
      message: ""
      observedGeneration: 5
      reason: SubnetsReady
      status: "True"
      type: SubnetsReady
    - lastTransitionTime: "2025-03-10T16:13:40Z"
      message: ""
      observedGeneration: 5
      reason: SecurityGroupsReady
      status: "True"
      type: SecurityGroupsReady
    - lastTransitionTime: "2025-03-10T16:13:40Z"
      message: ""
      observedGeneration: 5
      reason: InstanceProfileReady
      status: "True"
      type: InstanceProfileReady
    - lastTransitionTime: "2025-03-11T10:37:47Z"
      message: Controller isn't authorized to call ec2:RunInstances
      observedGeneration: 5
      reason: RunInstancesAuthCheckFailed
      status: "False"
      type: ValidationSucceeded
    - lastTransitionTime: "2025-03-11T10:38:33Z"
      message: ValidationSucceeded=False
      observedGeneration: 5
      reason: UnhealthyDependents
      status: "False"
      type: Ready
    instanceProfile: xxx_15843455441266977890
    securityGroups:
    - id: sg-041205f271ae25f96
      name: xxx-1147151999
    subnets:
    - id: subnet-00a466905da92a7cc
      zone: us-east-1c
      zoneID: use1-az1
    - id: subnet-0d0f5f00fc6e60d3b
      zone: us-east-1a
      zoneID: use1-az4
    - id: subnet-037a140aaa7934478
      zone: us-east-1b
      zoneID: use1-az6
kind: List
metadata:
  resourceVersion: ""
```

**Versions**:
- Kubernetes Version (`kubectl version`): 1.32

**Comment by Vormillion** [comment]
We suspect that something goes wrong here
```
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        encrypted: true
        iops: 3000
        throughput: 125
        volumeSize: 100Gi
        volumeType: gp3
```

We have policy to make spin EC2 instance only with encrypted EBS, but according to docs this piece of nodeclass didn't change between karpenter 1.2.x and 1.3.x but somehow rule complains that Karpenter tries to create EC2 with unencrypted EBS.

**Comment by obervinov** [comment]
We had a similar problem after upgrading to 1.3.1 with `EC2NodeClass NotReady`. Only recreating `ec2nodeclass` helps.
```yaml
apiVersion: v1
items:
- apiVersion: karpenter.k8s.aws/v1
  kind: EC2NodeClass
  metadata:
    name: generic
  spec:
    amiFamily: AL2023
    amiSelectorTerms:
    - alias: al2023@latest
    blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 25Gi
        volumeType: gp3
    metadataOptions:
      httpEndpoint: enabled
      httpProtocolIPv6: disabled
      httpPutResponseHopLimit: 1
      httpTokens: required
    role: Karpenter
    securityGroupSelectorTerms:
    - tags:
        Name: karpenter-node
    subnetSelectorTerms:
    - tags:
        Name: private-us-east-1a
  status:
    amis:
    - id: ami-006321160784caf3d
      name: amazon-eks-node-al2023-arm64-standard-1.31-v20250228
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: DoesNotExist
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: DoesNotExist
    - id: ami-0a89f636458f0aa4e
      name: amazon-eks-node-al2023-x86_64-nvidia-1.31-v20250228
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: Exists
    - id: ami-0b94752294befca8a
      name: amazon-eks-node-al2023-x86_64-standard-1.31-v20250228
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-gpu-count
        operator: DoesNotExist
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: DoesNotExist
    - id: ami-0ebe659725d068d62
      name: amazon-eks-node-al2023-x86_64-neuron-1.31-v20250228
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-accelerator-count
        operator: Exists
    conditions:
    - lastTransitionTime: "2025-02-07T11:10:35Z"
      message: ""
      observedGeneration: 4
      reason: AMIsReady
      status: "True"
      type: AMIsReady
    - lastTransitionTime: "2025-02-07T11:10:35Z"
      message: ""
      observedGeneration: 4
      reason: SubnetsReady
      status: "True"
      type: SubnetsReady
    - lastTransitionTime: "2025-02-07T11:10:35Z"
      message: ""
      observedGeneration: 4
      reason: SecurityGroupsReady
      status: "True"
      type: SecurityGroupsReady
    - lastTransitionTime: "2025-02-07T11:10:35Z"
      message: ""
      observedGeneration: 4
      reason: InstanceProfileReady
      status: "True"
      type: InstanceProfileReady
    - lastTransitionTime: "2025-02-07T12:50:00Z"
      message: ""
      observedGeneration: 4
      reason: ValidationSucceeded
      status: "True"
      type: ValidationSucceeded
    - lastTransitionTime: "2025-03-10T16:02:04Z"
      message: Failed to detect the cluster CIDR
      observedGeneration: 4
      reason: NodeClassNotReady
      status: "False"
      type: Ready
    instanceProfile: karpenter_16253362336087885606
    securityGroups:
    - id: sg-***
      name: karpenter-node-20240411124135217800000003
    subnets:
    - id: subnet-***
      zone: us-east-1a
      zoneID: use1-az1
kind: List
metadata:
  resourceVersion: ""
```

**Comment by Vormillion** [comment]
> We had a similar problem after upgrading to 1.3.1 with `EC2NodeClass NotReady`. Only recreating `ec2nodeclass` helps.
> 
> apiVersion: v1
> items:
> - apiVersion: karpenter.k8s.aws/v1
>   kind: EC2NodeClass
>   metadata:
>     name: generic
>   spec:
>     amiFamily: AL2023
>     amiSelectorTerms:
>     - alias: al2023@latest
>     blockDeviceMappings:
>     - deviceName: /dev/xvda
>       ebs:
>         deleteOnTermination: true
>         encrypted: true
>         volumeSize: 25Gi
>         volumeType: gp3
>     metadataOptions:
>       httpEndpoint: enabled
>       httpProtocolIPv6: disabled
>       httpPutResponseHopLimit: 1
>       httpTokens: required
>     role: Karpenter
>     securityGroupSelectorTerms:
>     - tags:
>         Name: karpenter-node
>     subnetSelectorTerms:
>     - tags:
>         Name: private-us-east-1a
>   status:
>     amis:
>     - id: ami-006321160784caf3d
>       name: amazon-eks-node-al2023-arm64-standard-1.31-v20250228
>       requirements:
>       - key: kubernetes.io/arch
>         operator: In
>         values:
>         - arm64
>       - key: karpenter.k8s.aws/instance-gpu-count
>         operator: DoesNotExist
>       - key: karpenter.k8s.aws/instance-accelerator-count
>         operator: DoesNotExist
>     - id: ami-0a89f636458f0aa4e
>       name: amazon-eks-node-al2023-x86_64-nvidia-1.31-v20250228
>       requirements:
>       - key: kubernetes.io/arch
>         operator: In
>         values:
>         - amd64
>       - key: karpenter.k8s.aws/instance-gpu-count
>         operator: Exists
>     - id: ami-0b94752294befca8a
>       name: amazon-eks-node-al2023-x86_64-standard-1.31-v20250228
>       requirements:
>       - key: kubernetes.io/arch
>         operator: In
>         values:
>         - amd64
>       - key: karpenter.k8s.aws/instance-gpu-count
>         operator: DoesNotExist
>       - key: karpenter.k8s.aws/instance-accelerator-count
>         operator: DoesNotExist
>     - id: ami-0ebe659725d068d62
>       name: amazon-eks-node-al2023-x86_64-neuron-1.31-v20250228
>       requirements:
>       - key: kubernetes.io/arch
>         operator: In
>         values:
>         - amd64
>       - key: karpenter.k8s.aws/instance-accelerator-count
>         operator: Exists
>     conditions:
>     - lastTransitionTime: "2025-02-07T11:10:35Z"
>       message: ""
>       observedGeneration: 4
>       reason: AMIsReady
>       status: "True"
>       type: AMIsReady
>     - lastTransitionTime: "2025-02-07T11:10:35Z"
>       message: ""
>       observedGeneration: 4
>       reason: SubnetsReady
>       status: "True"
>       type: SubnetsReady
>     - lastTransitionTime: "2025-02-07T11:10:35Z"
>       message: ""
>       observedGeneration: 4
>       reason: SecurityGroupsReady
>       status: "True"
>       type: SecurityGroupsReady
>     - lastTransitionTime: "2025-02-07T11:10:35Z"
>       message: ""
>       observedGeneration: 4
>       reason: InstanceProfileReady
>       status: "True"
>       type: InstanceProfileReady
>     - lastTransitionTime: "2025-02-07T12:50:00Z"
>       message: ""
>       observedGeneration: 4
>       reason: ValidationSucceeded
>       status: "True"
>       type: ValidationSucceeded
>     - lastTransitionTime: "2025-03-10T16:02:04Z"
>       message: Failed to detect the cluster CIDR
>       observedGeneration: 4
>       reason: NodeClassNotReady
>       status: "False"
>       type: Ready
>     instanceProfile: karpenter_16253362336087885606
>     securityGroups:
>     - id: sg-***
>       name: karpenter-node-20240411124135217800000003
>     subnets:
>     - id: subnet-***
>       zone: us-east-1a
>       zoneID: use1-az1
> kind: List
> metadata:
>   resourceVersion: ""

Well, that's not a solution for us as recreation will most likely restart all nodes.

**Comment by obervinov** [comment]
@Vormillion agree, and in our case we have a slightly different error `Failed to detect the cluster CIDR', but it seems that both errors are related to the IAM role.

**Comment by edibble21** [comment]
Have you modified your karpentercontrollerpolicy at all?

**Comment by Vormillion** [comment]
@edibble21 - no, I didn't touch Controller policy in IAM at all, I was comparing installation notes for <= 1.2 and 1.3 and policy looks the same (it's including ec2:runInstances)

**Comment by jonathan-innis** [comment]
Should be fixed by #7882. The RunInstances authorization call wasn't being properly modeled after the LaunchTemplate that we actually use for CreateFleet

**Comment by rkubik-hostersi** [comment]
@jonathan-innis do you have an idea when the release is to be expected?
Or, what IAM permissions should be added exactly, as this breaks the current operations ;) 

Thanks!

**Comment by rkubik-hostersi** [comment]
@jonathan-innis This issue still occurs after upgrading to version `1.3.3`. Can you re-open?
