### ISSUE TITLE
nodeclaim not found in disruption controller doesn't emit NodeClaimNotFoundError error label

### ISSUE THREAD

**Issue by k24dizzle** [aws/karpenter-provider-aws#8052]
### Description

**Observed Behavior**:
We have an alert on `karpenter_cloudprovider_errors_total`.

Recently this alerted for the `nodeclaim.disruption` controller.

<img width="1343" alt="Image" src="https://github.com/user-attachments/assets/f1b5340d-e777-461b-8562-c398a9fb3e1e" />

Checking the logs I do see the following.
```
{
    "level": "ERROR",
    "time": "2025-05-07T18:24:40.643Z",
    "logger": "controller",
    "message": "Reconciler error",
    "commit": "1c39126",
    "controller": "nodeclaim.disruption",
    "controllerGroup": "karpenter.sh",
    "controllerKind": "NodeClaim",
    "NodeClaim": {
        "name": "app-gvdk5"
    },
    "namespace": "",
    "name": "app-gvdk5",
    "reconcileID": "9bc9c98f-7112-47d6-92f5-ebb16a71a530",
    "error": "getting drift, resolving node class, ec2nodeclasses.karpenter.k8s.aws \"app-node\" is terminating, treating as not found"
}
```

**Expected Behavior**:

It would be nice if the metric that was emitted also have the `NodeClaimNotFoundError` error label set in this case.

**Reproduction Steps** (Please include YAML):
- Delete an ec2nc and wait for the disruption controller to run concurrently?

**Comment by engedaam** [comment]
I was able to reproduce this error using v1.3.2 of Karpenter. However, when I tested this for v1.4.x I found that this issue was fixed in that version. Are you able to update the Karpenter controller and see if that remediates this issue for you?

**Comment by k24dizzle** [comment]
I upgraded the controller to `v1.5.0` and still see this behavior

<img width="1500" alt="Image" src="https://github.com/user-attachments/assets/1b878776-5bd7-4bb5-aabf-e09dc1528812" />

**Comment by k24dizzle** [comment]
```
{"level":"ERROR","time":"2025-06-24T18:42:42.202Z","logger":"controller","message":"failed listing instance types for app-123 ","commit":"9458bb5","controller":"disruption","namespace":"","name":"","reconcileID":"...","error":"no subnets found"}
```

I see these logs which I assume is related
